# TODO

#######################################################################
# PGE configuration for L4_TROPO.
#######################################################################

# The runconfig section is intended to be used for dynamically generating the runconfig file used
# when running the OPERA PGEs. Any values set with a "__CHIMERA_VAL__" should be filled in by the input
# preprocessor. Otherwise, a precondition evaluation error will be raised by chimera.
#
# The runconfig section is also used as the data dict for the RunConfig jinja2 template.
# Accordingly, the schema here does NOT need to match the final RunConfig.yaml schema.
#
# * See RunConfig_schema.<label>.yaml for RunConfig.yaml documentation.
# * See related `RunConfig.yaml.<label>.jinja2.tmpl` file
#  and `util.conf_util.RunConfig.__init__()` for jinja2 usage.
runconfig:
  input_file_group:
    input_file_paths: __CHIMERA_VAL__
  dynamic_ancillary_file_group: {}
  input_file:
    input_file_path: __CHIMERA_VAL__
  processing:
    n_workers: __CHIMERA_VAL__
    threads_per_worker: __CHIMERA_VAL__
    max_memory: __CHIMERA_VAL__
  output_options:
    output_heights: []
  product_path_group:
    product_version: __CHIMERA_VAL__
    product_path: /home/ops/output_dir
    scratch_path: /home/ops/scratch_dir
    dask_temp_dir: tmp 
#  processing:
#    algorithm_parameters: __CHIMERA_VAL__
  cnm_version: "__CHIMERA_VAL__"

# This lists all the precondition evaluation steps that this PGE needs to run prior to running the PGE.
preconditions:
  - get_product_version
  - get_cnm_version
  - set_daac_product_type

# This lists all the postprocessor steps that this PGE will run after running the PGE.
postprocess:
  - update_product_accountability

get_product_version:
  version_key: "TROPO_PRODUCT_VERSION"

set_daac_product_type:
  template: OPERA_L4_TROPO_{cnm_version}

# This function will add to the PGE output metadata when product to dataset conversion is performed
set_extra_pge_output_metadata:
   daac_product_type: daac_product_type

# List the extensions that the PGE generates
output_types:
  L4_TROPO:
    - nc
    - png
    - catalog.json
    - iso.xml
    - log
    - qa.log

# The PGE name
# This must MATCH the corresponding entry in pge_outputs.yaml
pge_name: "L4_TROPO"

# Set the primary input/output types here
primary_input: "TROPO_ROW"
primary_output: "L4_TROPO"

# List the groups that Chimera will need to localize
# The entries MUST reference a property of `$.runconfig` of this YAML.
# The referenced properties MUST be maps.
localize_groups:
  - input_file_group


#######################################################################
# PGE Simulation Mode
#
# * See PGE_SIMULATION_MODE in settings.yaml and it's usage
# * See SIMULATE_OUTPUTS usage in opera_pge_wrapper.py and chimera.precondition_evaluator.py
#######################################################################
input_file_base_name_regexes:
    - '(?P<id>(?P<project>ECMWF)_(?P<product_type>TROP)_(?P<acquisition_ts>(?P<acq_year>\d{4})(?P<acq_month>\d{2})(?P<acq_day>\d{2})(?P<acq_hour>\d{2})(?P<acq_minute>\d{2}))_(?P<creation_ts>(?P<cre_year>\d{4})(?P<cre_month>\d{2})(?P<cre_day>\d{2})(?P<cre_hour>\d{2})(?P<cre_minute>\d{2}))_(?P<product_version>\d+))$'
sample_input_dataset_id: "ECMWF_TROP_201501010000_201501010000_1.nc"
output_base_name: OPERA_L4_TROPO_{tile_id}_{acquisition_ts}Z_{creation_ts}Z_{sensor}_{spacing}_v{product_version}
ancillary_base_name: OPERA_L4_TROPO_{creation_ts}Z_{sensor}_{spacing}_v{product_version}
