# TODO

#######################################################################
# PGE configuration for L3_DIST_S1.
#######################################################################

# The runconfig section is intended to be used for dynamically generating the runconfig file used
# when running the OPERA PGEs. Any values set with a "__CHIMERA_VAL__" should be filled in by the input
# preprocessor. Otherwise, a precondition evaluation error will be raised by chimera.
#
# The runconfig section is also used as the data dict for the RunConfig jinja2 template.
# Accordingly, the schema here does NOT need to match the final RunConfig.yaml schema.
#
# * See RunConfig_schema.<label>.yaml for RunConfig.yaml documentation.
# * See related `RunConfig.yaml.<label>.jinja2.tmpl` file
#  and `util.conf_util.RunConfig.__init__()` for jinja2 usage.
runconfig:
  input_file_group:
    pre_rtc_copol: __CHIMERA_VAL__
    pre_rtc_crosspol: __CHIMERA_VAL__
    post_rtc_copol: __CHIMERA_VAL__
    post_rtc_crosspol: __CHIMERA_VAL__
    prev_product: __CHIMERA_VAL__
  mgrs_tile_id: __CHIMERA_VAL__
  src_water_mask_path: __CHIMERA_VAL__
  apply_water_mask: __CHIMERA_VAL__
  product_path_group:
    product_version: __CHIMERA_VAL__
    input_path: /home/ops/input_dir
    product_path: /home/ops/output_dir
    scratch_path: /home/ops/scratch_dir
  cnm_version: "__CHIMERA_VAL__"

# This lists all the precondition evaluation steps that this PGE needs to run prior to running the PGE.
preconditions:
  - get_product_version
  - get_cnm_version
  - set_daac_product_type
  - get_dist_s1_rtc_s3_paths
  - get_dist_s1_prev_product
  - get_dist_s1_mgrs_tile
  - get_dist_s1_mask_file

# This lists all the postprocessor steps that this PGE will run after running the PGE.
postprocess:
  - update_product_accountability

get_product_version:
  version_key: "DIST_S1_PRODUCT_VERSION"

set_daac_product_type:
  template: OPERA_L3_DIST_S1_{cnm_version}

get_dist_s1_mask_file:
  s3_bucket: "opera-umd-water-mask"
  s3_key: "v1/EPSG4326.vrt"

# This function will add to the PGE output metadata when product to dataset conversion is performed
set_extra_pge_output_metadata:
   daac_product_type: daac_product_type

# List the extensions that the PGE generates
output_types:
  L3_DIST_S1:
    - tif
    - png
    - catalog.json
    - iso.xml
    - log
    - qa.log

# The PGE name
# This must MATCH the corresponding entry in pge_outputs.yaml
pge_name: "L3_DIST_S1"

# Set the primary input/output types here
primary_input: "L2_RTC_S1"
primary_output: "L3_DIST_S1"

# Must be set to true to ensure algorithm parameter template is instantiated
# for every DSWx-S1 job
use_algorithm_parameters: true

# List the groups that Chimera will need to localize
# The entries MUST reference a property of `$.runconfig` of this YAML.
# The referenced properties MUST be maps.
localize_groups:
  - input_file_group


#######################################################################
# PGE Simulation Mode
#
# * See PGE_SIMULATION_MODE in settings.yaml and it's usage
# * See SIMULATE_OUTPUTS usage in opera_pge_wrapper.py and chimera.precondition_evaluator.py
#######################################################################
input_file_base_name_regexes:
    - '(?P<id>(?P<project>OPERA)_(?P<level>L2)_(?P<product_type>RTC)-(?P<source>S1)_(?P<burst_id>\w{4}-\w{6}-\w{3})_(?P<acquisition_ts>(?P<acq_year>\d{4})(?P<acq_month>\d{2})(?P<acq_day>\d{2})T(?P<acq_hour>\d{2})(?P<acq_minute>\d{2})(?P<acq_second>\d{2})Z)_(?P<creation_ts>(?P<cre_year>\d{4})(?P<cre_month>\d{2})(?P<cre_day>\d{2})T(?P<cre_hour>\d{2})(?P<cre_minute>\d{2})(?P<cre_second>\d{2})Z)_(?P<sensor>S1[A-D])_(?P<spacing>30)_(?P<product_version>v\d+[.]\d+))$'
sample_input_dataset_id: "OPERA_L2_RTC-S1_T047-100908-IW3_20200702T231843Z_20230305T140222Z_S1B_30_v0.1"
output_base_name: OPERA_L3_DIST-ALERT-S1_{tile_id}_{acquisition_ts}Z_{creation_ts}Z_{sensor}_{spacing}_v{product_version}
ancillary_base_name: OPERA_L3_DIST-S1_{creation_ts}Z_{sensor}_{spacing}_v{product_version}
