# TODO

#######################################################################
# PGE configuration for L4_TROPO.
#######################################################################

# The runconfig section is intended to be used for dynamically generating the runconfig file used
# when running the OPERA PGEs. Any values set with a "__CHIMERA_VAL__" should be filled in by the input
# preprocessor. Otherwise, a precondition evaluation error will be raised by chimera.
#
# The runconfig section is also used as the data dict for the RunConfig jinja2 template.
# Accordingly, the schema here does NOT need to match the final RunConfig.yaml schema.
#
# * See RunConfig_schema.<label>.yaml for RunConfig.yaml documentation.
# * See related `RunConfig.yaml.<label>.jinja2.tmpl` file
#  and `util.conf_util.RunConfig.__init__()` for jinja2 usage.
runconfig:
  input_file_group:
    input_file_paths: __CHIMERA_VAL__
  dynamic_ancillary_file_group: {}
  processing:
    n_workers: __CHIMERA_VAL__
    threads_per_worker: __CHIMERA_VAL__
    max_memory: __CHIMERA_VAL__
  output_options:
    output_heights:
      - -500.0
      - -300.0
      - -200.0
      - -100.0
      - -50.0
      - -20.0
      - -10.0
      - 0.0
      - 10.0
      - 30.96
      - 53.92
      - 79.04
      - 106.54
      - 136.62
      - 169.51
      - 205.44
      - 244.69
      - 287.52
      - 334.24
      - 385.16
      - 440.61
      - 500.95
      - 566.54
      - 637.76
      - 715.02
      - 798.72
      - 889.29
      - 987.15
      - 1092.73
      - 1206.44
      - 1328.7
      - 1459.91
      - 1600.44
      - 1750.63
      - 1910.76
      - 2081.09
      - 2261.8
      - 2452.99
      - 2654.69
      - 2866.83
      - 3089.25
      - 3321.67
      - 3563.69
      - 3814.82
      - 4074.41
      - 4341.73
      - 4615.92
      - 4896.02
      - 5180.98
      - 5469.3
      - 5759.3
      - 6049.89
      - 6340.68
      - 6631.66
      - 6922.8
      - 7214.09
      - 7505.51
      - 7797.04
      - 8088.67
      - 8380.36
      - 8672.11
      - 8963.9
      - 9255.7
      - 9547.49
      - 9839.26
      - 10130.98
      - 10422.64
      - 10714.22
      - 11005.69
      - 11297.93
      - 11592.86
      - 11890.24
      - 12190.1
      - 12492.44
      - 12797.3
      - 13104.7
      - 13414.65
      - 13727.18
      - 14042.3
      - 14360.05
      - 14680.44
      - 15003.5
      - 15329.24
      - 15657.7
      - 15988.88
      - 16322.83
      - 16659.55
      - 16999.08
      - 17341.62
      - 17687.77
      - 18038.35
      - 18394.25
      - 18756.34
      - 19125.61
      - 19503.09
      - 19889.88
      - 20286.66
      - 20694.9
      - 21114.77
      - 21546.62
      - 21990.82
      - 22447.75
      - 22917.85
      - 23401.71
      - 23900.02
      - 24413.5
      - 24942.93
      - 25489.15
      - 26053.04
      - 26635.56
      - 27237.73
      - 27860.64
      - 28505.47
      - 29173.5
      - 29866.09
      - 30584.71
      - 31330.96
      - 32106.57
      - 32915.27
      - 33763.05
      - 34652.52
      - 35586.89
      - 36569.72
      - 37604.95
      - 38696.94
      - 39850.56
      - 41071.2
      - 42364.93
      - 43738.55
      - 45199.69
      - 46756.98
      - 48413.94
      - 50159.36
      - 51996.21
      - 53905.62
      - 55882.68
      - 57930.78
      - 60053.46
      - 62254.39
      - 64537.43
      - 66906.53
      - 69365.77
      - 71918.79
      - 74584.91
      - 80301.65 
  product_path_group:
    product_version: __CHIMERA_VAL__
    product_path: /home/ops/output_dir
    scratch_path: /home/ops/scratch_dir
    dask_temp_dir: tmp 
#  processing:
#    algorithm_parameters: __CHIMERA_VAL__
  cnm_version: "__CHIMERA_VAL__"

# This lists all the precondition evaluation steps that this PGE needs to run prior to running the PGE.
preconditions:
  - get_product_version
  - get_cnm_version
  - set_daac_product_type
  - get_tropo_input_filepaths

# This lists all the postprocessor steps that this PGE will run after running the PGE.
postprocess:
  - update_product_accountability

get_product_version:
  version_key: "TROPO_PRODUCT_VERSION"

set_daac_product_type:
  template: OPERA_L4_TROPO_{cnm_version}

# This function will add to the PGE output metadata when product to dataset conversion is performed
set_extra_pge_output_metadata:
   daac_product_type: daac_product_type

# List the extensions that the PGE generates
output_types:
  L4_TROPO:
    - nc
    - png
    - catalog.json
    - iso.xml
    - log
    - qa.log

# The PGE name
# This must MATCH the corresponding entry in pge_outputs.yaml
pge_name: "L4_TROPO"

# Set the primary input/output types here
primary_input: "TROPO_ROW"
primary_output: "L4_TROPO"

# List the groups that Chimera will need to localize
# The entries MUST reference a property of `$.runconfig` of this YAML.
# The referenced properties MUST be maps.
localize_groups:
  - input_file_group


#######################################################################
# PGE Simulation Mode
#
# * See PGE_SIMULATION_MODE in settings.yaml and it's usage
# * See SIMULATE_OUTPUTS usage in opera_pge_wrapper.py and chimera.precondition_evaluator.py
#######################################################################
input_file_base_name_regexes:
    - '(?P<id>(?P<project>ECMWF)_(?P<product_type>TROP)_(?P<acquisition_ts>(?P<acq_year>\d{4})(?P<acq_month>\d{2})(?P<acq_day>\d{2})(?P<acq_hour>\d{2})(?P<acq_minute>\d{2}))_(?P<creation_ts>(?P<cre_year>\d{4})(?P<cre_month>\d{2})(?P<cre_day>\d{2})(?P<cre_hour>\d{2})(?P<cre_minute>\d{2}))_(?P<product_version>\d+))$'
sample_input_dataset_id: "ECMWF_TROP_201501010000_201501010000_1"
output_base_name: OPERA_L4_TROPO-ZENITH_{acquisition_ts}Z_{creation_ts}Z_HRES_v{product_version}
ancillary_base_name: OPERA_L4_TROPO_{creation_ts}
