
MGRS_SET_STATE_CONFIG = 'dswx_ni-state-config'

STATE_CONFIG_TYPE = "state_config_type"
MGRS_SET_ID = "mgrs_set_id"
CYCLE_NUMBER = "cycle_number"
SENSING_DATE = "sensing_date"
IS_COMPLETE = "is_complete"
COMPLETENESS_REASON = "completeness_reason"
EXPECTED_TRACK_FRAMES = "expected_track_frames"
FOUND_TRACK_FRAMES = "found_track_frame"
MISSING_TRACK_FRAMES = "missing_track_frame"
POLARIZATION = "polarization"
LAND_OCEAN_FLAG = "land_ocean_flag"
BOUNDING_BOX = "bounding_box"
GCOV_PRODUCT_PATHS = "gcov_product_paths"
COVERAGE_ACTUAL = "coverage_actual"
COVERAGE_EXPECTED = "coverage_expected"
EXPIRATION_DATE = "expiration_date"
IS_EXPIRED = "is_expired"
