RunConfig:
  input_product: str()
  product_update_ancillaries: any(map(key=str()), null())
  product_update_params:
    subsample: int(min=1, required=False)
    new_version: str()
    update_processed_time: bool()
    update_product_id: bool()
  product_path_group:
    input_path: str()
    product_path: str()
    scratch_path: str()
