dswx_s1_granule_regex = (
r'(?P<id>'
r'(?P<project>OPERA)_'
r'(?P<level>L3)_'
r'(?P<product_type>DSWx)-'
r'(?P<source>S1)_'
r'(?P<tile_id>T[^\W_]{5})_'
r'(?P<acquisition_ts>(?P<acq_year>\d{4})(?P<acq_month>\d{2})(?P<acq_day>\d{2})T(?P<acq_hour>\d{2})(?P<acq_minute>\d{2})(?P<acq_second>\d{2})Z)_'
r'(?P<creation_ts>(?P<cre_year>\d{4})(?P<cre_month>\d{2})(?P<cre_day>\d{2})T(?P<cre_hour>\d{2})(?P<cre_minute>\d{2})(?P<cre_second>\d{2})Z)_'
r'(?P<sensor>S1A|S1B|S1C)_'
r'(?P<spacing>30)_'
r'(?P<product_version>v\d+[.]\d+)'
r')'
# r'('
# r'(_'
# r'(?P<band_index>B\d{2})_'
# r'(?P<band_name>WTR|BWTR|CONF|DIAG))|_BROWSE)?'
# r'[.]'
# r'(?P<ext>tif|tiff|png|iso\.xml)$'
)
