RunConfig:
  Name: str()

  Groups:
    PGE:
      PGENameGroup:
        PGEName: str(required=True)

      InputFilesGroup:
        InputFilePaths: list(str(), min=1, required=True)

      DynamicAncillaryFilesGroup:
        AncillaryFileMap: map(key=str(), min=0)

      ProductPathGroup:
        OutputProductPath: str(required=True)
        ScratchPath: str(required=True)

      PrimaryExecutable:
        ProductIdentifier: str(required=False)
        ProductVersion: any(str(), num(), required=False)
        CompositeReleaseID: str(required=False)
        ProgramPath: str(required=True)
        ProgramOptions: list(str(), min=0, required=False)
        ErrorCodeBase: int(required=True)
        SchemaPath: str(required=True)
        AlgorithmParametersSchemaPath: str(required=False)
        IsoTemplatePath: str(required=False)
        IsoMeasuredParameterDescriptions: str(required=False)
        DataValidityStartDate: int(min=20000101, max=21991231, required=False)

      QAExecutable:
        Enabled: bool(required=True)
        ProgramPath: str(required=False)
        ProgramOptions: list(str(), min=0, required=False)

      DebugLevelGroup:
        DebugSwitch: bool(required=False)
        ExecuteViaShell: bool(required=False)

    SAS:
      run_config:
        # A list of file paths or strings for pre-acquisition radar data in co-polarization.
        pre_rtc_copol: list(str(), required=True)

        # A list of file paths or strings for pre-acquisition radar data in cross-polarization.
        pre_rtc_crosspol: list(str(), required=True)

        # A list of file paths or strings for acquisition-time radar data in co-polarization.
        post_rtc_copol: list(str(), required=True)

        # A list of file paths or strings for acquisition-time data in cross-polarization.
        post_rtc_crosspol: list(str(), required=True)

        # Path to prior DIST-S1 product. If None, no prior product is used and confirmation is not performed.
        prior_dist_s1_product: str(required=False)

        # A string representing the MGRS (Military Grid Reference System) tile identifier for output product.
        mgrs_tile_id: str(required=True)

        # Path for scratch directory
        dst_dir: str(required=False)

        # Path for water mask ancillary input
        src_water_mask_path: any(str(), null(), required=False)

        # Toggle to utilize optional water mask ancillary input
        apply_water_mask: bool(required=False)

        # Path for directory where output product will be written
        product_dst_dir: str(required=False)

        # Path to external algorithm config file. If None, SAS defaults are used.
        algo_config_path: str(required=False)

        #
        input_data_dir: str(required=False)
