"""Constants for DISP-S1 evaluator state-config metadata fields."""

# State-config types (used as ES index suffix via grq_*_{type})
DISP_S1_CYCLE_STATE_CONFIG = "disp-s1-cycle-state-config"
DISP_S1_K_GROUP_STATE_CONFIG = "disp-s1-k-group-state-config"

# Per-cycle metadata keys
STATE_CONFIG_TYPE = "state_config_type"
FRAME_ID = "frame_id"
ACQUISITION_CYCLE = "acquisition_cycle"
DOWNLOAD_BATCH_ID = "download_batch_id"
EXPECTED_BURST_IDS = "expected_burst_ids"
FOUND_BURST_IDS = "found_burst_ids"
MISSING_BURST_IDS = "missing_burst_ids"
FOUND_CSLC_GRANULE_IDS = "found_cslc_granule_ids"
CSLC_PRODUCT_PATHS = "cslc_product_paths"
COVERAGE_ACTUAL = "coverage_actual"
COVERAGE_EXPECTED = "coverage_expected"
COVERAGE_PERCENTAGE = "coverage_percentage"
CYCLE_COMPLETE = "cycle_complete"

# K-group metadata keys
K_GROUP_INDEX = "k_group_index"
K = "k"
M = "m"
ACQUISITION_CYCLES = "acquisition_cycles"
CYCLE_STATE_CONFIG_IDS = "cycle_state_config_ids"
CYCLE_COMPLETENESS = "cycle_completeness"
CYCLES_COMPLETE = "cycles_complete"
CYCLES_EXPECTED = "cycles_expected"
ALL_CYCLES_COMPLETE = "all_cycles_complete"
TOTAL_CSLCS_FOUND = "total_cslcs_found"
TOTAL_CSLCS_EXPECTED = "total_cslcs_expected"
COMPRESSED_CSLC_SATISFIED = "compressed_cslc_satisfied"
COMPRESSED_CSLC_IDS = "compressed_cslc_ids"
IS_COMPLETE = "is_complete"
FORCE_SUBMIT = "force_submit"
DOWNLOAD_JOB_ID = "download_job_id"
